yarnPath: .yarn/releases/yarn-3.6.1.cjs
nodeLinker: node-modules

npmScopes:
  inhibitor1217:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"
